using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TakeItem : MonoBehaviour
{
    public GameObject head;  // 碑aY场 GameObject
    public GameObject body;  // 碑aō砰 GameObject
    public GameObject leg;   // 碑aL场 GameObject
    private void EquipItem(Item item)
    {
        SpriteRenderer itemSpriteRenderer = item.GetComponent<SpriteRenderer>();

        switch (item.itemType)
        {
            case Item.ItemType.Head:
                head.GetComponent<SpriteRenderer>().sprite = itemSpriteRenderer.sprite;  // 蠓sY场汗悉
                break;
            case Item.ItemType.Body:
                body.GetComponent<SpriteRenderer>().sprite = itemSpriteRenderer.sprite;  // 蠓sō砰汗悉
                break;
            case Item.ItemType.Leg:
                leg.GetComponent<SpriteRenderer>().sprite = itemSpriteRenderer.sprite;  // 蠓sL场汗悉
                break;
        }
    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        Item item = other.GetComponent<Item>();

        if (item != null)
        {
            // 具飒~岌蠓s杆称
            EquipItem(item);
            Debug.Log("Player picked up " + item.itemType);

            // 具峋P反~
            Destroy(other.gameObject);
        }
    }
}
